openapi: 3.0.0
info:
  title: Fidelite API
  version: 1.0.0
paths:
  /fidelite/verifyClientStatus:
    post:
      summary: Vérifie le statut du client
      requestBody:
        description: Objet Compensation en entrée
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Compensation'
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Compensation'
        '400':
          description: Mauvaise requête
          content:
            text/plain:
              example: "Erreur : Le statut du client est manquant."
        '500':
          description: Erreur interne du serveur
          content:
            text/plain:
              example: "Erreur interne du serveur."
components:
  schemas:
    Compensation:
      type: object
      properties:
        client:
          $ref: '#/components/schemas/Client'
    Client:
      type: object
      properties:
        status:
          type: string
