openapi: 3.0.3
info:
  description: PROJECT_SNCF API
  title: PROJECT_SNCF API
  version: 1.0.0
servers:
- url: https://PROJECT_SNCF
paths:
  /ticket/validity:
    post:
      operationId: isTicketValid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TicketValidationDataDTO'
          application/xml:
            schema:
              $ref: '#/components/schemas/TicketValidationDataDTO'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Response'
          description: OK
      summary: POST ticket/validity
      x-contentType: application/json
      x-accepts: '*/*'
components:
  schemas:
    TicketValidationDataDTO:
      example:
        idTicket: 0
        salt: 5
        idVenue: 6
        idVendor: 1
        key: key
      properties:
        idTicket:
          format: int32
          type: integer
        idVenue:
          format: int32
          type: integer
        idVendor:
          format: int32
          type: integer
        salt:
          format: int64
          type: integer
        key:
          type: string
      type: object
    Response:
      properties: {}
      type: object

